name: Security Scan

on:
  pull_request:

jobs:
  grype-security-scan:
    runs-on: ubuntu-latest
    name: Grype
    permissions:
      contents: read
      security-events: write
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      - name: Security Scan
        id: grype-scan
        uses: anchore/scan-action@e1165082ffb1fe366ebaf02d8526e7c4989ea9d2 # v7.4.0
        with:
          path: "."
          fail-build: true
          only-fixed: true
          severity-cutoff: "high"
          output-format: "sarif"

      - name: Upload scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@95e58e9a2cdfd71adc6e0353d5c52f41a045d225 # v4
        with:
          sarif_file: ${{ steps.grype-scan.outputs.sarif }}
          category: "grype"
