name: Security Scan

on:
  pull_request:

jobs:
  grype-security-scan:
    runs-on: ubuntu-latest
    name: Grype
    permissions:
      contents: read
      security-events: write
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
      - name: Security Scan
        id: grype-scan
        uses: anchore/scan-action@e1165082ffb1fe366ebaf02d8526e7c4989ea9d2 # v7.4.0
        with:
          path: "."
          fail-build: true
          only-fixed: true
          severity-cutoff: "high"
          output-format: "sarif"

      - name: Upload scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@ff2f1c621b7f889edc0d3c761ac2e6a3f8cdb0dd # v4.37.7
        with:
          sarif_file: ${{ steps.grype-scan.outputs.sarif }}
          category: "grype"
